version: "3.9"

name: polaris-flash-cards

services:
  database:
    image: postgres:16
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POLARIS_FLASH_CARDS_DB}
      POSTGRES_USER: ${POLARIS_FLASH_CARDS_DB_USER}
      POSTGRES_PASSWORD: ${POLARIS_FLASH_CARDS_DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data


  polaris-flash-cards:
    build:
      context: ../.
      dockerfile: ./infrastructure/Dockerfile
    depends_on:
      - database
    container_name: polaris-flash-cards
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/${POLARIS_FLASH_CARDS_DB}
      SPRING_DATASOURCE_USERNAME: ${POLARIS_FLASH_CARDS_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${POLARIS_FLASH_CARDS_DB_PASSWORD}
volumes:
  postgres_data: